import type { Metadata } from "next";
import "./globals.css";

import { Poppins } from "next/font/google";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased flex items-center justify-center w-full `}
      >
        <div className="max-w-[400px] border-2 w-full">{children}</div>
      </body>
    </html>
  );
}
