import type { Metadata } from "next";
import "./globals.css";

import { Poppins } from "next/font/google";
import { ThemeProvider } from "@/components/util/theme-provider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
  },
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased flex items-center justify-center w-full`}
        style={{
          width: "400px",
          margin: "0 auto",
          transformOrigin: "top center",
          boxSizing: "border-box",
          border: "1px solid #ccc",
        }}
      >
        <ThemeProvider
          attribute="class"
          forcedTheme="light" 
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
