import type { Metadata, Viewport } from "next";
import "./globals.css";

import { Poppins } from "next/font/google";
import { ThemeProvider } from "@/components/util/theme-provider";
import { ReactQueryProvider } from "@/components/util/query-provider";
import { ConvexClientProvider } from "@/components/util/convex-provider";
import { PeerProvider } from "@/components/util/peerjs-provider";
import { getUser } from "@/lib/auth/server-actions";
import { Toaster } from "@/components/ui/sonner";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.className} antialiased flex items-center justify-center `}
      >
        <ReactQueryProvider>
          <ThemeProvider
            attribute="class"
            forcedTheme="light"
            disableTransitionOnChange
          >
            <ConvexClientProvider>
              <PeerProvider>
                <div className="max-w-md w-full border box-content">
                  {children}
                  <Toaster />
                </div>
              </PeerProvider>
            </ConvexClientProvider>
          </ThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
